name: Check Charger Availability

concurrency:
  group: charger-check
  cancel-in-progress: true

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
            TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}
            CHARGER_ID: ${{ secrets.CHARGER_ID }}
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          for i in {1..5}
          do
            echo "Execution $i"
            node checkCharger.js
            sleep 60
          done

      - name: Commit state if changed
        run: |
          git config user.name "juanfranbustos"
          git config user.email "juanfranbustosc@gmail.com"
          git add state.json || true
          git diff --cached --quiet || git commit -m "Update state"
          git push

